version: "3.7"
services: 
  app:
    build:
      context: .
      args:
        JAR_FILE: "target/app.jar"
    container_name: portal-backend
    ports:
      - "8080:8080"
    links:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://root:root@db-mongo:27017
      REDIS_URI: db-redis:6379
  
  mongo:
    # https://hub.docker.com/_/mongo?tab=description
    image: mongo:latest
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis:latest
    container_name: db-redis
    ports:
      - "6379:6379"