
server:
  port: 8000

spring:
  data:
    mongodb:
      uri: ${MONDO_URI:mongodb://portal:portal@localhost:27017}/portal
  jpa:
    hibernate:
      ddl-auto: update

gitlab:
  host: http://localhost:8080
  # client-name: PortalBackend
  client-id: 090de64bbf77d3c11abd158643ffa3c68574ca5fa470346f2eefd51de615ecfc
  client-secret: 54b82ee69632ed5c6098773468f252c056b8d61b969f14ae7ba23d3ab2da6de9
  redirect-uri: http://localhost:8000/gitlab/redirect
  auth-uri-code: ${gitlab.host}/oauth/authorize?client_id=${gitlab.client-id}&redirect_uri=${gitlab.redirect-uri}&response_type=code&state={0}
  auth-uri-token: ${gitlab.host}/oauth/token?client_id=${gitlab.client-id}&client_secret=${gitlab.client-secret}&code={0}&grant_type=authorization_code&redirect_uri=${gitlab.redirect-uri}
  api:
    projects: ${gitlab.host}/api/v4/projects
    project-members: ${gitlab.host}/api/v4/projects/{0}/members
    project-commits: ${gitlab.host}/api/v4/projects/{0}/repository/commits