
server:
  port: 8000

spring:
  data:
    mongodb:
      uri: ${MONDO_URI:mongodb://portal:portal@localhost:27017}/portal
  jpa:
    hibernate:
      ddl-auto: update

github:
  scope: repo admin:org admin:public_key gist notifications user
  client-id: b921b0294b501968709f
  client-secret: 945bc7659236faad4f9fd5b1dde15a671459dce8
  redirect-uri: http://luncert.cn:18080/github/redirect
  api:
    authorize: https://github.com/login/oauth/authorize?client_id=${github.client-id}&redirect_uri=${github.redirect-uri}&scope=${github.scope}&state={0}
    token: https://github.com/login/oauth/access_token?client_id=${github.client-id}&client_secret=${github.client-secret}&redirect_uri=${github.redirect-uri}&code={0}&state={1}
    # ---------------------------
    commits: https://api.github.com/repos/{0}/{1}/commits
    repositories: https://api.github.com/user/repos
    weekly-commit-count: https://api.github.com/repos/{0}/{1}/stats/participation